### ISSUE TITLE
Can't open output file for writing: bin/skhd

### ISSUE THREAD

**Issue by skipadu** [koekeishiya/homebrew-formulae#21]
## Description
I tried to install skhd, but it was having an issue with it.
I have Xcode Commandline tools installed and accepted the terms.

I ran the following:
`brew install koekeishiya/formulae/skhd`

And the output is here:
```
==> Downloading https://github.com/koekeishiya/skhd/archive/v0.3.5.zip
Already downloaded: /Users/skipadu/Library/Caches/Homebrew/downloads/24a17a4e7a0e673a71aca0bae86c282978e35fcde5a4e0797de49290974c9d28--skhd-0.3.5.zip
==> Installing skhd from koekeishiya/formulae
==> make install
Last 15 lines from /Users/skipadu/Library/Logs/Homebrew/skhd/01.make:
2022-04-07 10:52:21 +0000

make
install

rm -rf ./bin
mkdir -p ./bin
clang src/skhd.c -std=c99 -O3 -framework Carbon -framework CoreServices -o bin/skhd
ld: can't open output file for writing: bin/skhd, errno=2 for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [bin/skhd] Error 1
```

## Details

macOS Monterey 12.3.1 (21E258)
Apple M1 Max

**Comment by ptomasroos** [comment]
If you use

```
brew install --HEAD koekeishiya/formulae/skhd
```

You will get the build fix from master which hasn't been released AFAIK

**Comment by skipadu** [comment]
When tried to use:
`brew install --HEAD koekeishiya/formulae/skhd`

Will still get the error:

```
Running `brew update --preinstall`...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
Updated 4 formulae.

==> Cloning https://github.com/koekeishiya/skhd.git
Cloning into '/Users/skipadu/Library/Caches/Homebrew/skhd--git'...
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
==> Installing skhd from koekeishiya/formulae
==> make install
Last 15 lines from /Users/skipadu/Library/Logs/Homebrew/skhd/01.make:
2022-04-20 19:41:38 +0000

make
install

rm -rf ./bin
mkdir -p ./bin
clang src/skhd.c -std=c99 -Wall -O2 -framework Cocoa -framework Carbon -framework CoreServices -o bin/skhd
ld: can't open output file for writing: bin/skhd, errno=2 for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [bin/skhd] Error 1
```

**Comment by ndlarsen** [comment]
Experiencing the same issue regardless of referencing HEAD or not. New to the Mac stuff bit am being told I am on a 2019 pro. To be honest, this sounds like a permission issue, after all the script is attempting to install into `/bin`.

**Comment by ndlarsen** [comment]
> just do it manually.
> 
> `git clone https://github.com/koekeishiya/skhd.git`
> 
> `cd skhd`
> 
> `make install`
> 
> `make`
> 
> Once done you will see a bin folder. You can either create a soft link to the skhd binary or create an alias in your zshrc/bashrc file

While this is entirely possible, it ~~sort of~~ defeats the point of a brew formulae.

**Comment by deadchase** [comment]
Having the same issue.

**Comment by katoby** [comment]
I managed to get it to work. I am a bit afraid to retest it because I went through a hassle to get it to work. Below is proof its working with brew:

`[~]
 # brew services info skhd
skhd (homebrew.mxcl.skhd)
Running: ✔
Loaded: ✔
Schedulable: ✘
User: user
PID: 1624`

Steps were simple:
`xcode-select --install` then
`brew install --HEAD koekeishiya/formulae/skhd`

It could have been a coincidence but please let me know guys if this worked for you.

**Comment by aussieboi** [comment]
![Screen Shot 2022-07-01 at 09 33 51](https://user-images.githubusercontent.com/2497323/176847091-a9a2b9ef-6e0e-4f23-a5eb-f22e2362e6c0.png)

after trying everything in comments, still not working @ M1 Max

**Comment by aussieboi** [comment]
fixe 

> ![Screen Shot 2022-07-01 at 09 33 51](https://user-images.githubusercontent.com/2497323/176847091-a9a2b9ef-6e0e-4f23-a5eb-f22e2362e6c0.png)
> 
> after trying everything in comments, still not working @ M1 Max

fixed by doing:

brew install koekeishiya/formulae/skhd --HEAD


"--HEAD" at the endw

**Comment by skipadu** [comment]
> Worked as mentioned above with `brew install --HEAD koekeishiya/formulae/skhd`, _but_ i had to do a `brew cleanup` before the command to get it working eventually.

Now back to using skhd, thanks to you. This did the trick :)
