### ISSUE TITLE
caveats: show instructions about `sip` and  `visudo` (display the string already interpolated using `whoami`/`sha256`)

### ISSUE THREAD

**Issue by devnoname120** [koekeishiya/homebrew-formulae#22]
**References**:
- https://github.com/koekeishiya/yabai/wiki/Disabling-System-Integrity-Protection
- https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#macos-big-sur-and-monterey---automatically-load-scripting-addition-on-startup

**Comment by otahontas** [comment]
I think a caveat about configuring scripting addition with visudo should be shown (pretty easy to forget to update checksums otherwise)
