### ISSUE TITLE
Formula `skhd` has not implemented #plist, #service or installed a locatable service file

### ISSUE THREAD

**Issue by devondalebro** [koekeishiya/homebrew-formulae#36]
When I try to start yabai or skhd with `brew services start yabai` I get 

Formula `skhd` has not implemented #plist, #service or installed a locatable service file

**Comment by ShahriarDhruvo** [comment]
I get the same issue with both skhd and yabai

**Comment by Cocophotos** [comment]
I have the same issue and I've looked at the code in master and then the code few months ago. The plist info has been removed in profit of using `yabai --start-service. The same goes for `skhd`. I do not have many homebrew services installed, so I do not know if the changes affect all homebrew services. But at least for `yabai`and `skhd`, there is an easy fix.

**Comment by ShahriarDhruvo** [comment]
So basically you are saying instead of using `brew services start yabai` we should use `yabai --start-service` and same goes for skhd? `skhd --start-service`

**Comment by Cocophotos** [comment]
> So basically you are saying instead of using `brew services start yabai` we should use `yabai --start-service` and same goes for skhd? `skhd --start-service`

Yes exactly! I've tried it, it's working

**Comment by ShahriarDhruvo** [comment]
Thanks it works.
I have updated my script like this:

```
# stop/start/restart yabai
# ctrl + alt - q : brew services stop yabai
ctrl + alt - q : yabai --stop-service
# ctrl + alt - s : brew services start yabai
ctrl + alt - s : yabai --start-service
# ctrl + alt - r : brew services restart yabai
ctrl + alt - r : yabai --restart-service
```

**Comment by koekeishiya** [comment]
https://github.com/koekeishiya/yabai/blob/master/CHANGELOG.md#504---2023-05-01

**Comment by devondalebro** [comment]
Oh no but when I run `yabai --start-service` it now says `Load failed: 5: Input/output error
Try running `launchctl bootstrap` as root for richer errors.`

**Comment by koekeishiya** [comment]
https://github.com/koekeishiya/yabai/issues/1731

**Comment by DasterSociety** [comment]
> I have the same issue and I've looked at the code in master and then the code few months ago. The plist info has been removed in profit of using `yabai --start-service`. The same goes for `skhd`. I do not have many homebrew services installed, so I do not know if the changes affect all homebrew services. But at least for `yabai`and `skhd`, there is an easy fix.

Thanks a lot. it worked for me

**Comment by devnoname120** [comment]
See https://github.com/asmvik/yabai/issues/1619#issuecomment-1507686308
