### ISSUE TITLE
Error installing KHD through homebrew

### ISSUE THREAD

**Issue by Esrelith** [koekeishiya/homebrew-formulae#5]
If I try installing KHD, it gives me this error:
>make
>install
>
>rm -rf ./bin
>mkdir -p ./bin
>clang src/khd.m -std=gnu89 -O3 -framework Carbon -framework Cocoa -framework IOKit -o >bin/khd
>In file included from src/khd.m:27:
>src/emulate.m:62:53: error: use of undeclared identifier 'NSEventTypeSystemDefined'
>    NSEvent *KeyEvent = [NSEvent otherEventWithType:NSEventTypeSystemDefined
                                                    ^
>1 error generated.
>make: *** [bin/khd] Error 1

How do I fix this?

**Comment by koekeishiya** [comment]
Should be fixed now. Install with: `brew install khd --HEAD`

**Comment by Esrelith** [comment]
Thanks!
